"""Vercel serverless function entry point for Proto-Gen API."""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List
import os

# Create FastAPI app
app = FastAPI(
    title="Proto-Gen API",
    version="1.0.0",
    description="AI-powered laboratory protocol generation and troubleshooting assistant"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Basic models
class ProtocolGenerationRequest(BaseModel):
    experimental_goal: str = Field(..., min_length=10)
    technique: str = Field(..., min_length=2)
    reagents: str = Field(..., min_length=3)
    template: str = Field(..., min_length=3)
    num_reactions: Optional[str] = Field("1")
    other_params: Optional[str] = Field(None)
    llm_provider: str = Field("gemini")

class ProtocolResponse(BaseModel):
    success: bool
    protocol: str
    provider_used: str
    error: Optional[str] = None

# Routes
@app.get("/")
async def root():
    return {
        "message": "Welcome to Proto-Gen API",
        "version": "1.0.0",
        "docs": "/docs"
    }

@app.get("/api/test")
async def api_test():
    return {"message": "API routing works!", "path": "/api/test"}

@app.get("/api/v1/test")
async def api_v1_test():
    return {"message": "API v1 routing works!", "path": "/api/v1/test"}

@app.get("/api/v1/health")
async def health_check():
    return {
        "status": "healthy",
        "version": "1.0.0",
        "available_providers": ["gemini"]
    }

@app.get("/api/v1/techniques")
async def get_techniques():
    return {
        "techniques": [
            {"value": "PCR", "label": "PCR"},
            {"value": "qPCR", "label": "qPCR"},
            {"value": "Gibson Assembly", "label": "Gibson Assembly"},
            {"value": "Miniprep", "label": "Miniprep"},
            {"value": "Gel Electrophoresis", "label": "Gel Electrophoresis"}
        ]
    }

@app.post("/api/v1/generate")
async def generate_protocol(request: ProtocolGenerationRequest):
    try:
        # Simple mock response for now
        protocol_text = f"""# Protocol: {request.technique}

## Objective
{request.experimental_goal}

## Materials
- {request.reagents}
- {request.template}

## Procedure
1. Prepare your workspace and materials
2. Follow standard {request.technique} protocol
3. Process {request.num_reactions} reaction(s)

## Notes
- This is a simplified protocol generated by Proto-Gen
- For detailed protocols, ensure your Gemini API key is configured
- Additional parameters: {request.other_params or 'None specified'}

*Generated using {request.llm_provider} provider*
"""
        
        return ProtocolResponse(
            success=True,
            protocol=protocol_text,
            provider_used=request.llm_provider
        )
    
    except Exception as e:
        return ProtocolResponse(
            success=False,
            protocol="",
            provider_used="",
            error=str(e)
        )

# Export the app for Vercel
app = app
